services: 
  postgres_dev:
    container_name: 'postgres-dev'
    image: 'postgres:16.0-alpine3.18'
    env_file: ../.env
    ports:
      - '54320:5432'
    volumes:
      - postgres_data:/data/postgres
volumes:
  postgres_data:

